### ISSUE TITLE
Error: undefined method `cry?' for Formulary::Formulae::Liquidsoap:Class

### ISSUE THREAD

**Issue by mcfiredrill** [drfill/homebrew-liquidsoap#18]
Tried to run a `brew upgrade` tonight and this blew up on me.

```
$ brew upgrade
Error: undefined method `cry?' for Formulary::Formulae::Liquidsoap:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/drfill/homebrew-liquidsoap/Formula/liquidsoap.rb:149:in `<class:Liquidsoap>'
/usr/local/Library/Taps/drfill/homebrew-liquidsoap/Formula/liquidsoap.rb:132:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/formula.rb:493:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:491:in `map'
/usr/local/Library/Homebrew/formula.rb:491:in `installed'
/usr/local/Library/Homebrew/cmd/upgrade.rb:9:in `upgrade'
/usr/local/Library/brew.rb:135:in `<main>'
```

**Comment by grahams** [comment]
I'm also having this same issue.  Also occurs with 'brew outdated'

**Comment by grahams** [comment]
Anyone have a workaround or solution for this?

**Comment by toots** [comment]
I can't reproduce.. Can you guys tell me more about this?

**Comment by grahams** [comment]
Well, any time I try to do ANYTHING with the liquidsoap Formula I get the above stack trace...  Even 'brew info liquidsoap' triggers it.  This was including 'brew upgrade' or 'brew outdated' like the OP suggested..  This was cramping my day so I ended up uninstalling liquidsoap so I could still upgrade other applications.

I just updated to the latest (and saw a new rev of liquidsoap come thru today)..

brew doctor output is:

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install ocaml-ogg

Run `brew missing` for more details.
Error: Failed to import: liquidsoap
undefined method `cry?' for Formulary::Formulae::Liquidsoap:Class

**Comment by grahams** [comment]
FYI: ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
My OS is 10.10.1

**Comment by mcfiredrill** [comment]
@toots I am on ruby 2.2 as well. What is your ruby version?

**Comment by tg90nor** [comment]
I am seeing this error when trying to install liquidsoap.
Ruby version 2.1.2, OS X 10.10.1

**Comment by LabLayers** [comment]
![image](https://cloud.githubusercontent.com/assets/607807/5929650/c9f27930-a653-11e4-990b-972afd8a37b9.png)

Same issue here.

**Comment by grahams** [comment]
fix works for me, thanks!

**Comment by toots** [comment]
Awesome, thanks for testing.

2015-01-28 14:38 GMT+01:00 Sean Graham <notifications@github.com>:

**Comment by LabLayers** [comment]
Works for me, thanks! :+1:

**Comment by mcfiredrill** [comment]
Works now, thanks!
