### ISSUE TITLE
configure: error: Cannot find camlp4o

### ISSUE THREAD

**Issue by toannq177** [drfill/homebrew-liquidsoap#20]
Hi there,

I am having this error while installing liquidsoap using homebrew. 

Warning: MD5 support is deprecated and will be removed in a future version.
Please switch this formula to SHA1 or SHA256.
==> ./configure --prefix=/usr/local/Cellar/ocaml-camomile/0.8.3
checking for ocamllex.opt... ocamllex.opt
checking for ocamlyacc... ocamlyacc
checking for ocamlweb... true
checking for camlp4o... no
configure: error: Cannot find camlp4o.

I install camlp4 using homebrew, I check and see camlp4o there in /usr/local/bin, but it is said not found. Any clue?

Thanks

**Comment by toannq177** [comment]
*brew install --env=std liquidsoap* works

**Comment by toannq177** [comment]
*brew install --env=std liquidsoap* works

**Comment by jzync** [comment]
*brew install --env=std liquidsoap* didn't work for me. Now I'm getting this error:
ld: library not found for -lmagic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [dllmagic_stubs.so] Error 2
make[1]: *** [byte-code-library] Error 2
make: *** [all] Error 2

Please help. 
Thanks

**Comment by highacid** [comment]
Kosmos:~ kosmos$ brew install --env=std liquidsoap
==> Installing liquidsoap from drfill/homebrew-liquidsoap
==> Installing dependencies for liquidsoap: ocaml-camomile, libmagic, ocaml-magic, ocaml-easy-format, ocaml-biniou, ocaml-cppo, ocaml-yojson, libogg, ocaml-ogg, libvorbis, ocaml-vorbis, libpng, freetype, libzip, jpeg, fontconfig, libtiff, gd, ocaml-gd4o, ocaml-mm
==> Installing liquidsoap dependency: ocaml-camomile
==> Downloading http://sourceforge.net/projects/camomile/files/camomile/0.8.3/camomile-0.8.3.tar.bz2
Already downloaded: /Library/Caches/Homebrew/ocaml-camomile-0.8.3.tar.bz2
Warning: MD5 support is deprecated and will be removed in a future version.
Please switch this formula to SHA1 or SHA256.
==> ./configure --prefix=/usr/local/Cellar/ocaml-camomile/0.8.3
==> make
==> make install OCAMLFIND_LDCONF=ignore
🍺  /usr/local/Cellar/ocaml-camomile/0.8.3: 980 files,  28M, built in 38 seconds
==> Installing liquidsoap dependency: libmagic
==> Downloading https://homebrew.bintray.com/bottles/libmagic-5.22.yosemite.bottle.3.tar.gz
######################################################################## 100.0%
==> Pouring libmagic-5.22.yosemite.bottle.3.tar.gz
🍺  /usr/local/Cellar/libmagic/5.22: 13 files, 3.3M
==> Installing liquidsoap dependency: ocaml-magic
==> Downloading http://sourceforge.net/projects/ocaml-magic/files/ocaml-magic/0.7/ocaml-magic-0.7.3.tar.gz
######################################################################## 100.0%
Warning: MD5 support is deprecated and will be removed in a future version.
Please switch this formula to SHA1 or SHA256.
==> ./configure
==> make
==> make install OCAMLFIND_LDCONF=ignore
🍺  /usr/local/Cellar/ocaml-magic/0.7.3: 13 files, 112K, built in 5 seconds
==> Installing liquidsoap dependency: ocaml-easy-format
==> Downloading http://mjambon.com/releases/easy-format/easy-format-1.0.1.tar.gz
######################################################################## 100.0%
Warning: MD5 support is deprecated and will be removed in a future version.
Please switch this formula to SHA1 or SHA256.
==> make
==> make install
🍺  /usr/local/Cellar/ocaml-easy-format/1.0.1: 11 files,  96K, built in 2 seconds
==> Installing liquidsoap dependency: ocaml-biniou
==> Downloading https://github.com/mjambon/biniou/archive/v1.0.5.zip
######################################################################## 100.0%
==> make clean
==> make
==> make install
🍺  /usr/local/Cellar/ocaml-biniou/1.0.5: 47 files, 944K, built in 5 seconds
==> Installing liquidsoap dependency: ocaml-cppo
==> Downloading http://mjambon.com/cppo-0.9.2.tar.gz
######################################################################## 100.0%
Warning: MD5 support is deprecated and will be removed in a future version.
Please switch this formula to SHA1 or SHA256.
==> make
==> make install
🍺  /usr/local/Cellar/ocaml-cppo/0.9.2: 5 files, 1.2M, built in 3 seconds
==> Installing liquidsoap dependency: ocaml-yojson
==> Downloading http://mjambon.com/yojson-1.0.3.tar.gz
######################################################################## 100.0%
Warning: MD5 support is deprecated and will be removed in a future version.
Please switch this formula to SHA1 or SHA256.
==> make
==> make install
🍺  /usr/local/Cellar/ocaml-yojson/1.0.3: 10 files, 928K, built in 6 seconds
==> Installing liquidsoap dependency: libogg
==> Downloading https://homebrew.bintray.com/bottles/libogg-1.3.2.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libogg-1.3.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libogg/1.3.2: 95 files, 672K
==> Installing liquidsoap dependency: ocaml-ogg
==> Downloading http://downloads.sourceforge.net/project/savonet/ocaml-ogg/0.4.5/ocaml-ogg-0.4.5.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/ocaml-ogg/0.4.5
==> make
==> make install OCAMLFIND_LDCONF=ignore
🍺  /usr/local/Cellar/ocaml-ogg/0.4.5: 15 files, 244K, built in 4 seconds
==> Installing liquidsoap dependency: libvorbis
==> Downloading https://homebrew.bintray.com/bottles/libvorbis-1.3.5.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libvorbis-1.3.5.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libvorbis/1.3.5: 155 files, 2.6M
==> Installing liquidsoap dependency: ocaml-vorbis
==> Downloading http://sourceforge.net/projects/savonet/files/ocaml-vorbis/0.6.1/ocaml-vorbis-0.6.1.tar.gz
######################################################################## 100.0%
Warning: MD5 support is deprecated and will be removed in a future version.
Please switch this formula to SHA1 or SHA256.
==> ./configure --prefix=/usr/local/Cellar/ocaml-vorbis/0.6.1
==> make
==> make install OCAMLFIND_LDCONF=ignore
🍺  /usr/local/Cellar/ocaml-vorbis/0.6.1: 16 files, 192K, built in 5 seconds
==> Installing liquidsoap dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.16.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libpng-1.6.16.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.16: 17 files, 1.3M
==> Installing liquidsoap dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.5.5.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring freetype-2.5.5.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.5.5: 60 files, 2.6M
==> Installing liquidsoap dependency: libzip
==> Downloading https://homebrew.bintray.com/bottles/libzip-0.11.2.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring libzip-0.11.2.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/libzip/0.11.2: 81 files, 536K
==> Installing liquidsoap dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring jpeg-8d.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/jpeg/8d: 18 files, 776K
==> Installing liquidsoap dependency: fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.11.1.yosemite.bottle.3.tar.gz
######################################################################## 100.0%
==> Pouring fontconfig-2.11.1.yosemite.bottle.3.tar.gz
==> /usr/local/Cellar/fontconfig/2.11.1/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.11.1: 448 files, 3.6M
==> Installing liquidsoap dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.3.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libtiff-4.0.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.0.3: 254 files, 3.8M
==> Installing liquidsoap dependency: gd
==> Downloading https://homebrew.bintray.com/bottles/gd-2.1.0_2.yosemite.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring gd-2.1.0_2.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/gd/2.1.0_2: 33 files, 1.3M
==> Installing liquidsoap dependency: ocaml-gd4o
==> Downloading http://sourceforge.net/projects/gd4o/files/gd4o/1.0%20Alpha%205/gd4o-1.0a5.tar.gz
######################################################################## 100.0%
Warning: MD5 support is deprecated and will be removed in a future version.
Please switch this formula to SHA1 or SHA256.
==> make all
==> make opt
==> make install OCAMLFIND_LDCONF=ignore
🍺  /usr/local/Cellar/ocaml-gd4o/1.0a5: 13 files, 256K, built in 5 seconds
==> Installing liquidsoap dependency: ocaml-mm
==> Downloading http://downloads.sourceforge.net/project/savonet/ocaml-mm/0.2.1/ocaml-mm-0.2.1.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/ocaml-mm/0.2.1
==> make
==> make install OCAMLFIND_LDCONF=ignore
🍺  /usr/local/Cellar/ocaml-mm/0.2.1: 37 files, 1.1M, built in 10 seconds
==> Installing liquidsoap
==> Downloading http://sourceforge.net/projects/savonet/files/liquidsoap/1.1.1/liquidsoap-1.1.1.tar.bz2
######################################################################## 100.0%
==> Patching
patching file src/decoder/aac_decoder.ml
patching file src/decoder/decoder.ml
patching file src/decoder/external_decoder.ml
patching file src/decoder/image/ppm_decoder.ml
patching file src/encoder/external_encoder.ml
patching file src/encoder/gstreamer_encoder.ml
patching file src/encoder/wav_encoder.ml
patching file src/io/alsa_io.ml
patching file src/io/gstreamer_io.ml
patching file src/io/oss_io.ml
patching file src/io/udp_io.ml
patching file src/outputs/alsa_out.ml
patching file src/protocols/mpd.ml
patching file src/sources/alsa_in.ml
patching file src/sources/external_input.ml
patching file src/sources/http_source.ml
patching file src/stream/aFrame.ml
patching file src/synth/keyboard.ml
patching file src/tools/http.ml
patching file src/tools/tutils.ml
patching file src/tools/utils.ml
patching file src/tools/wav.ml
==> ./configure --prefix=/usr/local/Cellar/liquidsoap/1.1.1 --with-user=kosmos --with-group=staff --with-default-font=/Library/Fonts/Verdana.ttf --disable-ldconf --disable-graphics
==> make
==> make install
==> Caveats
* There are no PulseAudio support
        Reason: Build Failure (https://github.com/mxcl/homebrew/pull/9226)
* There are no camlimages support
        Reason: Build Failure
==> Summary
🍺  /usr/local/Cellar/liquidsoap/1.1.1: 25 files, 7.5M, built in 21 seconds

**Comment by Acubed** [comment]
I seem to be affected by this too. Same error as reported. `brew install --env=std liquidsoap` works.

**Comment by toots** [comment]
Should be fixed now.
